server:
  port: 8140

spring:
  application:
    name: zCloud2ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuheyong/z_cloud2_config_repo.git
#          如果Git仓库需要权限访问
#          username:
#          password:
encrypt:
  key: wenyixicodedog

#eureka:
#  client:
#    service-url: http://localhost:8120/eureka/